### ISSUE TITLE
Got "500 Internal Server Error" When setting NTP ProtocolEnabled

### ISSUE THREAD

**Issue by Julia-Delta** [openbmc/phosphor-time-manager#11]
I added the newest modified source about phosphor-time-manager ([this](https://github.com/openbmc/phosphor-time-manager/commit/e101030b37eb8f64616a33eb0ef71d67a19bf7d7))
But I always got  "500 internal server error" and set failed
For example, I want to set ntp service disabled by redfish command
![image](https://github.com/user-attachments/assets/e609598e-49bd-4bba-aa6e-46a5fe323ab3)
I got the error message, and ProtocolEnabled's value still be true
![image](https://github.com/user-attachments/assets/10324e51-aec4-4d25-8293-abbb652eb4c0)
Check BMC console, I saw the systemd-timedated service reloading failed beacause of timeout
And a error message "systemd-timesyncd.service: Stopping unit: Invalid argument"
![image](https://github.com/user-attachments/assets/ffe1795a-c397-4084-ab52-f9b1c3f444aa)

If I send the redfish command again, the value was changed and service was good.
![image](https://github.com/user-attachments/assets/ccbdc39a-8c92-482d-ad24-fa8ff7d63aed)
![image](https://github.com/user-attachments/assets/64992918-4133-43ff-8d2e-52f506c2d79f)

Dose anyone have the same issue?

**Comment by geissonator** [comment]
I'm not a time-manager expert but your info above hints at not being on the latest and greatest of openbmc/openbmc. It's also not clear to me what system you're running here and if it's QEMU based or real hardware. There's not much we can do as a community if you are running downstream code or a machine that is not supported in upstream code.

With that said, there have been issues with hitting systemd with a reload at certain times during the boot of the BMC. It's a bigger issue when running in slower simulation or on AST2500 hardware. I have not seen any issues recently with the latest upstream code and our romulus QEMU model.

**Comment by Julia-Delta** [comment]
Yes, I used AST2500 hardware, and our team members developed on v2.14 version a lot of functions.
v2.14 version was the newest stable source, this was the reason why we chosed.
So updating code base is not our option.

On this version (systemd version was 254.4) ,  NTP enable/disable set from redfish has 500 internal server error issue.
Could you ponit out  any fixed patch which based on v2.14 to help me modify and finish this issue?

**Comment by williamspatrick** [comment]
There is no such thing as a "stable release" in the project.  No one on the project currently maintains point releases.  These are created just as useful points in time for people who insist on using a "release" for their work, but you're on your own for support.  The majority of users of the project work off HEAD.
