### ISSUE TITLE
Capitalization in types doesn't match README

### ISSUE THREAD

**Issue by robers97** [openbmc/phosphor-time-manager#3]
https://github.com/openbmc/phosphor-time-manager/blob/master/types.hpp

shows what appears valid:

 *  Host    Its only IPMI_SEL_SEL_TIME that will set the time on BMC.
     *          Meaning, IPMI_GET_SEL_TIME and request to get BMC time will
     *          result in same value.

README references HOST

Ditto for Manual...  Since NTP and BMC are capitalized this consistent, the other options are confusing.

**Comment by matthewfischer** [comment]
I vote we close this. The referenced sections in the hpp file and README are long gone and I found the readme quite clear.
